[package]
name = "tcr"
version = "0.1.0"
authors = ["rebekah <rebekahmercer@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bn = "0.4.3"
rand = "~0.3.14"
